export const COMPANY_CONFIG_TABLE_CHARGES = 'TABLE_CHARGES';
export const KIDS_DISCOUNT = 'KIDS_DISCOUNT';
export const DAILY_STOCK_UPDATE = 'DAILY_STOCK_UPDATE';
export const TAKE_AWAY_TAX = 'TAKE_AWAY_TAX';
export const EAT_IN_TAX = 'EAT_IN_TAX';
export const DEFAULT_LANGUAGE = 'DEFAULT_LANGUAGE';

export const DISPLAY_ITEM_AMOUNT_PER_PORTION = 'DISPLAY_ITEM_AMOUNT_PER_PORTION';
export const DISPLAY_ITEM_COOKING_TIME = 'DISPLAY_ITEM_COOKING_TIME';
export const DISPLAY_ITEM_CALORIES = 'DISPLAY_ITEM_CALORIES';
export const DISPLAY_ITEM_TAKE_OUT = 'DISPLAY_ITEM_TAKE_OUT';

export const CASH = 'CASH';
export const CREDIT_CARD = 'CREDIT_CARD';
export const PROCESSING = 'PROCESSING';

export const IS_FIRST_VISIT = 'IS_FIRST_VISIT';
export const IS_FIRST_VISIT_ANSWER_YES = 'YES';
export const IS_FIRST_VISIT_ANSWER_NO = 'NO';
